module Evergreen.Migrate.V4 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V3.Types
import Evergreen.V4.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V3.Types.FrontendModel -> ModelMigration Evergreen.V4.Types.FrontendModel Evergreen.V4.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V3.Types.BackendModel -> ModelMigration Evergreen.V4.Types.BackendModel Evergreen.V4.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V3.Types.FrontendMsg -> MsgMigration Evergreen.V4.Types.FrontendMsg Evergreen.V4.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V3.Types.ToBackend -> MsgMigration Evergreen.V4.Types.ToBackend Evergreen.V4.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V3.Types.BackendMsg -> MsgMigration Evergreen.V4.Types.BackendMsg Evergreen.V4.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V3.Types.ToFrontend -> MsgMigration Evergreen.V4.Types.ToFrontend Evergreen.V4.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_Card : Evergreen.V3.Types.Card -> Evergreen.V4.Types.Card
migrate_Types_Card old =
    { suit = old.suit |> migrate_Types_Suit
    , rank = old.rank |> migrate_Types_Rank
    }


migrate_Types_Rank : Evergreen.V3.Types.Rank -> Evergreen.V4.Types.Rank
migrate_Types_Rank old =
    case old of
        Evergreen.V3.Types.Ace ->
            Evergreen.V4.Types.Ace

        Evergreen.V3.Types.Five ->
            Evergreen.V4.Types.Five

        Evergreen.V3.Types.Six ->
            Evergreen.V4.Types.Six

        Evergreen.V3.Types.Seven ->
            Evergreen.V4.Types.Seven

        Evergreen.V3.Types.Eight ->
            Evergreen.V4.Types.Eight

        Evergreen.V3.Types.Nine ->
            Evergreen.V4.Types.Nine

        Evergreen.V3.Types.Ten ->
            Evergreen.V4.Types.Ten

        Evergreen.V3.Types.Jack ->
            Evergreen.V4.Types.Jack

        Evergreen.V3.Types.Queen ->
            Evergreen.V4.Types.Queen

        Evergreen.V3.Types.King ->
            Evergreen.V4.Types.King


migrate_Types_Suit : Evergreen.V3.Types.Suit -> Evergreen.V4.Types.Suit
migrate_Types_Suit old =
    case old of
        Evergreen.V3.Types.Clubs ->
            Evergreen.V4.Types.Clubs

        Evergreen.V3.Types.Diamonds ->
            Evergreen.V4.Types.Diamonds

        Evergreen.V3.Types.Hearts ->
            Evergreen.V4.Types.Hearts

        Evergreen.V3.Types.Spades ->
            Evergreen.V4.Types.Spades


migrate_Types_ToBackend : Evergreen.V3.Types.ToBackend -> Evergreen.V4.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V3.Types.NoOpToBackend ->
            Evergreen.V4.Types.NoOpToBackend

        Evergreen.V3.Types.JoinGame p0 ->
            Evergreen.V4.Types.JoinGame p0

        Evergreen.V3.Types.Reset ->
            Evergreen.V4.Types.Reset

        Evergreen.V3.Types.Played p0 ->
            Evergreen.V4.Types.Played (p0 |> migrate_Types_Card)

        Evergreen.V3.Types.Gathered ->
            Evergreen.V4.Types.Gathered

        Evergreen.V3.Types.TrumpChanged p0 ->
            Evergreen.V4.Types.TrumpChanged (p0 |> migrate_Types_Suit)



migrate_Types_ToFrontend : Evergreen.V3.Types.ToFrontend -> Evergreen.V4.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V3.Types.NoOpToFrontend ->
            Evergreen.V4.Types.NoOpToFrontend

        Evergreen.V3.Types.PlayersList p0 ->
            Evergreen.V4.Types.PlayersList p0

        Evergreen.V3.Types.GiveHand p0 ->
            Evergreen.V4.Types.GiveHand (p0 |> List.map migrate_Types_Card)

        Evergreen.V3.Types.PlayedBy p0 p1 ->
            Evergreen.V4.Types.PlayedBy p0 (p1 |> migrate_Types_Card)

        Evergreen.V3.Types.ClearPlayed ->
            Evergreen.V4.Types.ClearPlayed

        Evergreen.V3.Types.NewTrump p0 ->
            Evergreen.V4.Types.NewTrump (p0 |> migrate_Types_Suit)
