module Evergreen.Migrate.V9 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V7.Types
import Evergreen.V9.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V7.Types.FrontendModel -> ModelMigration Evergreen.V9.Types.FrontendModel Evergreen.V9.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V7.Types.BackendModel -> ModelMigration Evergreen.V9.Types.BackendModel Evergreen.V9.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V7.Types.FrontendMsg -> MsgMigration Evergreen.V9.Types.FrontendMsg Evergreen.V9.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V7.Types.ToBackend -> MsgMigration Evergreen.V9.Types.ToBackend Evergreen.V9.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V7.Types.BackendMsg -> MsgMigration Evergreen.V9.Types.BackendMsg Evergreen.V9.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V7.Types.ToFrontend -> MsgMigration Evergreen.V9.Types.ToFrontend Evergreen.V9.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_Card : Evergreen.V7.Types.Card -> Evergreen.V9.Types.Card
migrate_Types_Card old =
    { suit = old.suit |> migrate_Types_Suit
    , rank = old.rank |> migrate_Types_Rank
    }


migrate_Types_FrontendMsg : Evergreen.V7.Types.FrontendMsg -> Evergreen.V9.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V7.Types.UrlClicked p0 ->
            Evergreen.V9.Types.UrlClicked p0

        Evergreen.V7.Types.UrlChanged p0 ->
            Evergreen.V9.Types.UrlChanged p0

        Evergreen.V7.Types.UpdateName p0 ->
            Evergreen.V9.Types.UpdateName p0

        Evergreen.V7.Types.StartGame ->
            Evergreen.V9.Types.StartGame

        Evergreen.V7.Types.PlayCard p0 ->
            Evergreen.V9.Types.PlayCard (p0 |> migrate_Types_Card)

        Evergreen.V7.Types.GatherCards ->
            Evergreen.V9.Types.GatherCards

        Evergreen.V7.Types.ChangeTrump p0 ->
            Evergreen.V9.Types.ChangeTrump (p0 |> migrate_Types_Suit)

        Evergreen.V7.Types.NextRound ->
            Evergreen.V9.Types.NextRound

        Evergreen.V7.Types.NoOpFrontendMsg ->
            Evergreen.V9.Types.NoOpFrontendMsg


migrate_Types_Rank : Evergreen.V7.Types.Rank -> Evergreen.V9.Types.Rank
migrate_Types_Rank old =
    case old of
        Evergreen.V7.Types.Ace ->
            Evergreen.V9.Types.Ace

        Evergreen.V7.Types.Five ->
            Evergreen.V9.Types.Five

        Evergreen.V7.Types.Six ->
            Evergreen.V9.Types.Six

        Evergreen.V7.Types.Seven ->
            Evergreen.V9.Types.Seven

        Evergreen.V7.Types.Eight ->
            Evergreen.V9.Types.Eight

        Evergreen.V7.Types.Nine ->
            Evergreen.V9.Types.Nine

        Evergreen.V7.Types.Ten ->
            Evergreen.V9.Types.Ten

        Evergreen.V7.Types.Jack ->
            Evergreen.V9.Types.Jack

        Evergreen.V7.Types.Queen ->
            Evergreen.V9.Types.Queen

        Evergreen.V7.Types.King ->
            Evergreen.V9.Types.King


migrate_Types_Suit : Evergreen.V7.Types.Suit -> Evergreen.V9.Types.Suit
migrate_Types_Suit old =
    case old of
        Evergreen.V7.Types.Clubs ->
            Evergreen.V9.Types.Clubs

        Evergreen.V7.Types.Diamonds ->
            Evergreen.V9.Types.Diamonds

        Evergreen.V7.Types.Hearts ->
            Evergreen.V9.Types.Hearts

        Evergreen.V7.Types.Spades ->
            Evergreen.V9.Types.Spades


migrate_Types_ToBackend : Evergreen.V7.Types.ToBackend -> Evergreen.V9.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V7.Types.NoOpToBackend ->
            Evergreen.V9.Types.NoOpToBackend

        Evergreen.V7.Types.JoinGame p0 ->
            Evergreen.V9.Types.JoinGame p0

        Evergreen.V7.Types.Reset ->
            Evergreen.V9.Types.Reset

        Evergreen.V7.Types.Played p0 ->
            Evergreen.V9.Types.Played (p0 |> migrate_Types_Card)

        Evergreen.V7.Types.Gathered ->
            Evergreen.V9.Types.Gathered

        Evergreen.V7.Types.TrumpChanged p0 ->
            Evergreen.V9.Types.TrumpChanged (p0 |> migrate_Types_Suit)

        Evergreen.V7.Types.RestoreName ->
            Evergreen.V9.Types.RestoreName

        Evergreen.V7.Types.RestoreSession ->
            Evergreen.V9.Types.RestoreSession

        Evergreen.V7.Types.NextRoundRequested ->
            Evergreen.V9.Types.NextRoundRequested


migrate_Types_ToFrontend : Evergreen.V7.Types.ToFrontend -> Evergreen.V9.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V7.Types.NoOpToFrontend ->
            Evergreen.V9.Types.NoOpToFrontend

        Evergreen.V7.Types.PlayersList p0 ->
            Evergreen.V9.Types.PlayersList p0

        Evergreen.V7.Types.GiveHand p0 ->
            Evergreen.V9.Types.GiveHand (p0 |> List.map migrate_Types_Card)

        Evergreen.V7.Types.PlayedBy p0 p1 ->
            Evergreen.V9.Types.PlayedBy p0 (p1 |> migrate_Types_Card)

        Evergreen.V7.Types.ClearPlayed ->
            Evergreen.V9.Types.ClearPlayed

        Evergreen.V7.Types.NewTrump p0 ->
            Evergreen.V9.Types.NewTrump (p0 |> migrate_Types_Suit)

        Evergreen.V7.Types.RestoredName p0 ->
            Evergreen.V9.Types.RestoredName p0

        Evergreen.V7.Types.Scores p0 ->
            Evergreen.V9.Types.Scores p0
